trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

strategy:
  matrix:
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# - pwsh: |
#     echo ">>> Compile vscode-test"
#     yarn && yarn compile
#     echo ">>> Compiled vscode-test"
#     cd sample
#     echo ">>> Run sample integration test"
#     yarn && yarn compile && yarn test
#   displayName: Run Tests
#   env:
#     DISPLAY: ':99.0'