trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

strategy:
  matrix:
    windows:
      imageName: 'windows-latest'

pool:
  name: Default
  vmImage: $(imageName)

steps:

# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

- pwsh: |
    echo ">>> Publish"
    npm config set prefix E:\ProgramData\npm;
    npm install -g vsce --save-dev
    $Path = $Path + ";E:\ProgramData\npm\"
    . 'E:\ProgramData\npm\yarn.cmd' deploy;
  displayName: Publish Package
  env:
    DISPLAY: ':99.0'
    VSCE_PAT: $(VSCE_PAT)